### PR TITLE
Compatibility with Autoconf 2.70, import new ax_pthread.m4

### PR DESCRIPTION
**Pull request by thegushi**
Many macro renames for compatibility with autoconf 2.70
Re-importing ax_pthread (not ac_pthread as it was previously named)
Re-adding the github-version-string macro

Note that the res_nint and res_ndestroy commit is totally different from any of the overhaul changes to autoconf compatibility.

### CODE REVIEW

**Comment by gene-git** [comment]
I just build the 'testing' branch after removing my local patches - build completes fine with no errors or warnings - excellent.

Question - should I be using 'testing' branch now going forward instead of develop?

thanks for pushing this forward!!

**Comment by thegushi** [comment]
I'm hitting some FreeBSD issues with this change, so whatever I fixed for 2.70 seems broken for 2.69.  In a perfect world, for major changes like this, we'd spin the branch into one of it's own, rinse thoroughly, repeat, and then merge that in to develop.

Develop is where the regular action is likely to happen, but for something that will really cause damage, probably a new branch (atomic to that change), then develop after.

**Comment by martinbogo** [comment]
Everything should get merged into Develop.  Use "Testing" ( as in "testing
new Autoconf" ) to get this particular set of bugs quashed then after it's
merged back we will get rid of the testing branch.

( Let's try to use the best possible GitHub/Git and development
methodology.  One branch per related set of fixes, then merge back into
develop, which itself gets merged back into Master/Main when we cut
releases. )

-Martin

**Comment by gene-git** [comment]
Sounds good to me - thank you.
With autoconf 2.71 it builds cleanly here.

**Pull request merged**
