### PR TITLE
Fix a few potential crashes

### PR DESCRIPTION
**Pull request by klusark**
1. Fix missing from_domain check for store_dkim
2. Add checks for longer than buffer while parsing record

### CODE REVIEW

**Comment by martinbogo** [comment]
Compiling and testing this.

**Comment by martinbogo** [comment]
Joel, we have to do this one patch at a time.  I'm going to break this up into three PR's ( one per )

**Comment by klusark** [comment]
@martinbogo Sounds good. I can split it up as well if you like.

**Comment by martinbogo** [comment]
If you could take the time, I would definitely appreciate it.   It makes my
job as a maintainer easier!

**Comment by klusark** [comment]
@martinbogo I've opend #55 and #56. The second one has two of the commits since the last commit just adds a test.

**Comment by martinbogo** [comment]
Looks good, thank you

**Pull request closed without merging**
