### PR TITLE
Update schema.mysql

### LINKED ISSUE #98: schema.sql script error with MySQL 8.0.22
Line 31 of schema.sql thereabouts

``` sql
CREATE TABLE IF NOT EXISTS requests (
	id INT NOT NULL AUTO_INCREMENT,
	domain INT NOT NULL,
	repuri VARCHAR(255) NOT NULL,
        adkim TINYINT NOT NULL,
        aspf TINYINT NOT NULL,
        policy TINYINT NOT NULL,
        spolicy TINYINT NOT NULL,
        pct TINYINT NOT NULL,
        locked TINYINT NOT NULL DEFAULT '0',
	firstseen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastsent TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',

	PRIMARY KEY(id),
	KEY(lastsent),
	UNIQUE KEY(domain)
);
```

Error Code: 1067. Invalid default value for 'lastsent'

From: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

> The value inserted must not have a zero for the month part, the day part, or both parts. This is enforced beginning with MySQL 8.0.22, regardless of the server SQL mode setting.

What should the default value be instead?

This will execute and is the lowest acceptable date value: `lastsent TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00'`

### PR DESCRIPTION
**Pull request by bkeevil**
Change default date of lastseen to 1970-01-01

resolves #98

### CODE REVIEW

**Comment by bkeevil** [comment]
Issue 98

**Comment by martinbogo** [comment]
Please retarget to :develop so we can create the 1.4.1 from it per request of @mskucherawy

**Comment by martinbogo** [comment]
@thegushi ... can you give this a quick once-over to check sanity?

**Comment by thegushi** [comment]
My mysql server (not a typo) seems to be okay with this table as changed.  It's not 8.x, but the format looks correct.

Merging.

**Comment by thegushi** [comment]
Hey there,

Thanks for taking the time to help make our software better.  We'd love to be able to give you credit in our release notes, if you like.

Please let us know how we should credit you.  Common options are "anonymous", "username at github" "Real Name" or "Real Name (email@address)".  Preferably translated to ASCII if need be.

Best,

-Dan

**Comment by bkeevil** [comment]
I am always happy to help open source projects. I am fine with any format but Real Name is my preference.

**Pull request merged**
