### PR TITLE
Fix two build bugs

### PR DESCRIPTION
**Pull request by jikamens**
* Remove references to removed "docs" directory
* Fix earlier changes for detecting `res_ndestroy`

### CODE REVIEW

**Comment by martinbogo** [comment]
We're going to rework this patch slightly to work against the current 1.4.0 in the main/master branch.   This is pending a review by @thegushi.  

-Martin ( patch guru )

**Comment by thegushi** [comment]
Jikamens,

I've had to cherry-pick your changes a bit (friggin EVERYONE noticed the docs bug) and I also manually applied your changes while I was tweaking the configure.ac to be compatible with autoconf 2.70.  That said, we'd love to credit you for helping fix this.  Just let us know (here is fine, I'll see it in an email) how you'd like to be credited.  By default I just go with "username at github" but we can also do real name or real name/email address.  Whatever works for you in this privacy-centric world of GDPR.

I'm closing this one out and you can delete the branch you forked from (if this is the only commit on it).

Stay safe,

-Dan

**Comment by jikamens** [comment]
`Jonathan Kamens <jik@kamens.us>` is fine.

**Comment by celesteking** [comment]
So was `res_ndestroy` issue fixed? If so, why am I still getting it on `develop` branch?
```
/bin/libtool  --tag=CC   --mode=link gcc -std=gnu99  -I /usr/include/spf2 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -Wl,-z,relro  -L/usr/lib64/libspf2.so -o opendmarc-check opendmarc_check-opendmarc-check.o ../libopendmarc/libopendmarc.la -lresolv -lm -lspf2 -lbsd -lrt -lidn 
libtool: link: gcc -std=gnu99 -I /usr/include/spf2 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wl,-z -Wl,relro -o .libs/opendmarc-check opendmarc_check-opendmarc-check.o  -L/usr/lib64/libspf2.so ../libopendmarc/.libs/libopendmarc.so -lresolv -lm -lspf2 -lbsd -lrt -lidn
../libopendmarc/.libs/libopendmarc.so: undefined reference to `res_ndestroy'
collect2: error: ld returned 1 exit status
make[3]: *** [opendmarc-check] Error 1
```

**Comment by thegushi** [comment]
I believe it was fixed on the branch where we testing the changes to Autoconf, which may not have been merged into develop.  I will double check.

-Dan

**Pull request closed without merging**
